name: Code Formatting Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install CSharpier
      run: dotnet tool install --global csharpier --version 0.29.2

    - name: Check Format
      working-directory: src/TowerDefense.Api
      run: |
        # Run CSharpier in check mode
        dotnet csharpier --check .

